version: "3.8"
services:
  mysql-container:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecomuser
      MYSQL_PASSWORD: ${ECOM_DB_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSSWORD}
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  springboot-container:
    build:
      context: ./user-backend/ecommerce-spring-boot
      dockerfile: Dockerfile
    container_name: springboot-container
    depends_on:
      - mysql-container
    ports:
      - 8081:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
      ECOM_DB_PASS: ${ECOM_DB_PASS}
    restart: on-failure

  angular-container:
    build:
      context: ./user-frontend/user-web-app
      dockerfile: Dockerfile
    ports:
      - 81:80

volumes:
  db:
