version: "3.8"
services:
  springboot-container:
    build:
      context: ./user-backend/ecommerce-spring-boot
      dockerfile: Dockerfile
    container_name: springboot-container
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped

  angular-container:
    build:
      context: ./user-frontend/user-web-app
      dockerfile: Dockerfile
    ports:
      - 81:80
